version: '3.9'
services:
  db:
    image: postgres:14.0
    env_file: ./env/.env
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      quotes-network:
        ipv4_address: 173.40.0.11
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      - ./env:/env
    networks:
      quotes-network:
        ipv4_address: 173.40.0.12

volumes:
  db_data:

networks:
  quotes-network:
    driver: bridge
    ipam:
      config:
        - subnet: 173.40.0.0/16